#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

log "--------------- setup-env ---------------"

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    entries=$(find . -mindepth 1 -maxdepth 1)
    for entry in $entries; do
        execute rm -rf $to/$entry
        execute cp -r $entry $to/$entry
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    
	execute rm -f $to/$name
	execute cp -r $from $to/$name
}

execute mkdir -p "$HOME/.config"
execute mkdir -p "$HOME/.local"
execute mkdir -p "$HOME/.local/bin"
execute mkdir -p "$HOME/.local/scripts"
execute mkdir -p "$HOME/programs"

copy_dir .config $HOME/.config
copy_dir .local $HOME/.local
copy_file .ready-tmux $HOME
copy_file .tmux.conf $HOME
copy_file .p10k.zsh $HOME
copy_file .xprofile $HOME
copy_file .Xresources $HOME
copy_file .zshrc $HOME
