#!/usr/bin/env bash

# Enable Google Chrome repository and install Google Chrome
sudo dnf install -y fedora-workstation-repositories
sudo dnf config-manager setopt google-chrome.enabled=1 2>/dev/null || true
sudo dnf install -y google-chrome-stable
