#!/usr/bin/env bash

sudo dnf install curl git unzip xz zip libglu1-mesa

wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.7-stable.tar.xz

tar -xf flutter_linux_3.38.7-stable.tar.xz -C $HOME/programs/ -v
rm flutter_linux_3.38.7-stable.tar.xz
