#!/usr/bin/env bash

git clone https://github.com/neovim/neovim.git $HOME/programs/neovim
sudo dnf install -y cmake gettext lua5.1 liblua5.1-0-dev fzf

cd $HOME/programs/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
