#!/usr/bin/env bash

git clone -b stable/12 https://github.com/yshui/picom.git $HOME/programs/picom
sudo dnf install -y dbus-devel gcc git libconfig-devel libdrm-devel libev-devel libX11-devel libX11-xcb libxcb-devel libGL-devel libEGL-devel libepoxy-devel meson pcre2-devel pixman-devel uthash-devel xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel xcb-util-devel

cd $HOME/programs/picom
meson setup --buildtype=release build
sudo ninja -C build install
