#!/usr/bin/env bash

mkdir -p $HOME/programs
git clone https://github.com/tmux/tmux.git $HOME/programs/tmux
sudo dnf install -y aclocal libevent-devel ncurses-devel gcc make bison pkg-config
cd $HOME/programs/tmux
sh autogen.sh
./configure
make && sudo make install

# Install Tmux Plugin Manager (TPM)
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    mkdir -p "$HOME/.tmux/plugins"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

